name: Fetch Codeforces Contests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *' #北京时间0:00执行(UTC+8 16:00)
jobs:
  fetch-and-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch contests from Codeforces
      run: |
        python fetch_contests.py
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.PASSWORD }}